# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "hificnv"
description: Pacbio's copy number variant caller and depth visualization utlity
keywords:
  - sort
  - example
  - genomics
tools:
  - "hificnv":
      description: "Copy number variant caller and depth visualization utility for PacBio
        HiFi reads"
      homepage: "https://github.com/PacificBiosciences/HiFiCNV?tab=readme-ov-file"
      documentation: "https://github.com/PacificBiosciences/HiFiCNV?tab=readme-ov-file"
      tool_dev_url: "https://github.com/PacificBiosciences/HiFiCNV?tab=readme-ov-file"
      licence: ["Pacific Biosciences Software License Agreement"]
      identifier: ""
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1', single_end:false ]`
    - bam:
        type: file
        description: Sorted BAM
        pattern: "*.{bam}"
      ## TODO nf-core: Add a description of all of the variables used as output
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1', single_end:false ]`
    - fasta:
        type: file
        description: Fasta file used as the reference for the bam
        pattern: "*.{fasta}"
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1', single_end:false ]`
    - bed:
        type: file
        description: bed file with regions to exclude
        pattern: "*.{bam}"
output:
  - vcf:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1', single_end:false ]`
          pattern: "*.vcf.gz"
      - "*.vcf.gz":
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1', single_end:false ]`
          pattern: "*.vcf.gz"
  - depth_bw:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1', single_end:false ]`
          pattern: "*.bw"
      - "*depth.bw":
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1', single_end:false ]`
          pattern: "*.bw"
  - bedgraph:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1', single_end:false ]`
          pattern: "*.copynum.bedgraph"
      - "*.copynum.bedgraph":
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1', single_end:false ]`
          pattern: "*.copynum.bedgraph"
  - versions:
      - versions.yml:
          type: file
          description: File containing software versions
          pattern: "versions.yml"
authors:
  - "@tanyasarkjain"
maintainers:
  - "@tanyasarkjain"
